# Name: Judah Alter
# Date: 9/8/2025
# Assignment: (Assignment #1)
# Due Date: 9/12/2025
# About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes)
# Assumptions: (write any assumptions made here (ex: assumes correct user input))
# All work below was performed solely by Judah Alter.
# I [did used] code generated by an AI tool.

defect = 0 

import sys  # system functions
import random  # random number generation

defect = 0  # defect action
cooperate = 1  # cooperate action
roundCounter = 0  # round counter

def reward(MyAction , OpponentAction):
    if MyAction == defect and OpponentAction == defect:  # both defect
        return 1
    elif MyAction == defect and OpponentAction == cooperate:  # defect vs cooperate
        return 5
    elif MyAction == cooperate and OpponentAction == defect:  # cooperate vs defect
        return 0
    else:
        return 3  # both cooperate
    
def rangeReward(beg,end,myHistory,oppHistory):
    total = 0  # sum of rewards
    for i in range(beg,min(end,len(myHistory))):  # loop over range
        total += reward(myHistory[i],oppHistory[i])  # add reward
    return total  # return sum

def alwaysCooperate(myHistory,oppHistory):
    return cooperate  # always cooperate

def alwaysDefect(myHistory,oppHistory):
    return defect  # always defect

def probeAndLock(myHistory,oppHistory):
    if(len(myHistory) < 20):  # first 20 rounds
        return defect
    elif(len(myHistory) < 40):  # next 20 rounds
        return cooperate
    else:
        reward1=rangeReward(0,20,myHistory,oppHistory)  # sum rewards 0-19
        reward2=rangeReward(20,40,myHistory,oppHistory)  # sum rewards 20-39
        if reward1 > reward2:
            return defect
        else:
            return cooperate
        
def CheckProbeAndLock(myHistory,oppHistory):
    return probeAndLock(myHistory,oppHistory)  # callback function


def continiousProbe(myHistory,oppHistory):
    n=len(myHistory)  # current round
    if n== roundCounter:
        return defect  # end  defect
    if n==1:
        return cooperate  # 1st round  cooperate
    DSum = DCount = CSum = CCount = 0  # initialize the  sums
    for a, b in zip(myHistory, oppHistory):  # loop through history
        if a == defect:
            DSum += reward(a, b); DCount += 1  # defect sum counter stats
        else:
            CSum += reward(a, b); CCount += 1  # cooperate sum counter stats
    DAverage = DSum / DCount if DCount else 0.0  # avgerage defect
    CAverage = CSum / CCount if CCount else 0.0  # avgerage cooperate
    return cooperate if CAverage > DAverage else defect  # compare averages

def DefectUntilCooperate(myHistory,oppHistory):
    return cooperate if 1 in oppHistory else defect  # cooperate if opponent ever cooperated

def opponetCooperatePercentage(myHistory,oppHistory,ValCheck):
    if not oppHistory:
        return defect  # defect if no history
    else:
        rate = sum(1 for x in oppHistory if x == cooperate) / len(oppHistory)  # cooperation rate
        return cooperate if rate > ValCheck else defect  # compare to my threshold value
    
def opponentCooperate10Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.10) 

def opponetCooperate50Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.50) 
    
def opponetCooperate90Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.90)  

def randomChoice50(myHistory,oppHistory):
    return 1 if random.getrandbits(1) else 0  # random 0/1(had to look this up as its diff in c++)

def OriginalStrat(myHistory, oppHistory):
    defect, cooperate = 0, 1  # local actions
    # This function lets me probe the first three rounds, then adapt based on opponent behavior
    #By round 10, if they have mostly cooperated or mostly defected, I will defect
    #If I win (get 3 or 5) I will repeat my last move. if I lose (get 0 or 1) I will switch
    roundNum = len(myHistory)  # current round
    if roundNum == 0:
        return cooperate  # first i will cooperate
    if roundNum == 1:
        return defect  # second i will defect
    if roundNum == 2:
        return cooperate  # third i will cooperate
    #These are my preseed probing rounds
    
    def payoff(myAction, oppAction):  # payoff function
        if myAction == cooperate and oppAction == cooperate:
            return 3
        if myAction == cooperate and oppAction == defect:
            return 0
        if myAction == defect and oppAction == cooperate:
            return 5
        return 1
    oppCoops = sum(1 for move in oppHistory if move == cooperate)  # cooperate count
    coopRate = oppCoops / roundNum  # cooperate set rate
    if roundNum >= 10:
        if coopRate >= 0.80:
            return defect  
        if coopRate <= 0.20:
            return defect  
    lastMy = myHistory[-1]  
    lastOpp = oppHistory[-1]  
    lastPay = payoff(lastMy, lastOpp)  
    if lastPay in (3, 5):
        return lastMy  # repeat if win
    else:
        return cooperate if lastMy == defect else defect  # switch if loss
    # Note in order to see its result, you need to input 10 strategies, as it is the last one listed.


STRATEGIES = [
    ("alwaysCooperate", alwaysCooperate),
    ("alwaysDefect", alwaysDefect),
    ("probeAndLock", probeAndLock),
    ("continiousProbe", continiousProbe),
    ("defectUntilCooperate", DefectUntilCooperate),
    ("opponentCooperate10Percentage", opponentCooperate10Percent),
    ("opponentCooperate50Percentage", opponetCooperate50Percent),
    ("opponentCooperate90Percentage", opponetCooperate90Percent),
    ("random50", randomChoice50),
    ("OriginalStrat", OriginalStrat),
]

def PlayRound(GameA, GameB,Matches):
    AHistory = []  # A's moves
    BHistory = []  # B's moves
    ATotal = 0  # A's score
    BTotal = 0  # B's score
    for i in range(Matches):  # play rounds
        AMatch = GameA(AHistory, BHistory)  # A's move
        BMatch = GameB(BHistory, AHistory)  # B's move
        ATotal += reward(AMatch, BMatch)  # update A
        BTotal += reward(BMatch, AMatch)  # update B
        AHistory.append(AMatch)  # save A
        BHistory.append(BMatch)  # save B
    return ATotal, BTotal  # return scores

def main():

    defaultRound = 2000  # default rounds
    while True:
        try:
            roundsInput = input(f"Enter number of rounds (any non-negative integer, default {defaultRound}): ")  # get rounds
            if roundsInput.strip() == "":
                rounds = defaultRound  # use default
                break
            rounds = int(roundsInput)  # parse input
            if rounds >= 0:
                break
            else:
                print("Please enter a non-negative integer.")
        except ValueError:
            print("Please enter a valid integer.")
    maxK = len(STRATEGIES)  # max strategies
    defaultStrat = maxK  # default k is all strategies
    while True:
        try:
            k_input = input(f"Enter number of strategies to use (0 to {maxK}, default {defaultStrat}): ")  # get k
            if k_input.strip() == "":
                k = defaultStrat  # use default
                break
            k = int(k_input)  # parse input
            if 0 <= k <= maxK:
                break
            else:
                print(f"Please enter a number between 0 and {maxK}.")  
        except ValueError:
            print("Please enter a valid integer.")
    print(f"num_of_iterations: {rounds}, num_of_stratiges: {k}\n")  # show settings
    FunctionNames = STRATEGIES[:k]  # pick strategies
    totals = [0 for _ in range(len(FunctionNames))]  # init totals
    for i in range(len(FunctionNames)):
        for j in range(i+1, len(FunctionNames)):
            AName, AFunction = FunctionNames[i]  # get A
            BName, BFunction = FunctionNames[j]  # get B
            ATotal, BTotal = PlayRound(AFunction, BFunction, rounds)  # play
            totals[i] += ATotal  # add A
            totals[j] += BTotal  # add B
    for (name, _), total in zip(FunctionNames, totals):
        print(f"{name}: {total}")  # print results

if __name__ == "__main__":
    main()

















