# Name: Judah Alter
# Date: 9/26/2025
# Assignment: (Assignment #2)
# Due Date: 9/26/2025
# About this project: This project allows users to go over the top 30 downloads and users of a an Apache Web Access through a certain date, and understood through Combined Log Format.
# Assumptions: Assumes correct user input
# All work below was performed solely by Judah Alter.
# I [did used] code generated by an AI tool.


import sys
import collections
import datetime
import operator

_MIN_STRING = "01/01/0000"   # assignment default "start of time" (textual)
_MAX_STRING = "12/30/9999"   # assignment default "end of time" (textual)

def _parse_input_date(s):
   
   # keep the textual defaults for printing but map them internally to datetime.date.min/max.

    if s == _MIN_STRING:
        return datetime.date.min
    if s == _MAX_STRING:
        return datetime.date.max
    return datetime.datetime.strptime(s, "%m/%d/%Y").date()

def ParsingCLI(argument):
    
    # command line arugments.
    # Usage: python Alter_J_assignment2.py <apache_logs> <startdate> <enddate>
    # Date: MM/DD/YYYY
    # Should return (path,startTxt,endTxt,startDate,endDate)
   
    if len(argument) < 2:
        print("Usuage: python3 Alter_J_assignment2.py <logfilePath> <start_date> <end_date>")
        sys.exit(1)
        #This enforces my logfilePath argument

    path = argument[1]
    startTxt = argument[2] if len(argument) >= 3 else "01/01/0000"
    endTxt   = argument[3] if len(argument) >= 4 else "12/30/9999"

    try:
        start_date = _parse_input_date(startTxt)
        end_date   = _parse_input_date(endTxt)
    except ValueError:
        print("Error: Dates must be in MM/DD/YYYY format.")
        sys.exit(1)

    if end_date < start_date:
        print("Error: End date must be after start date.")
        sys.exit(1)

    return path, startTxt, endTxt, start_date, end_date


def ParseCLF(line):
    # Parses the CLF portion 
    
    try:
        host, rest = line.split(" ", 1)  # first token before first space = host

        # Extract date between [ ] and parse only dd/Mon/yyyy
        lb = rest.index("[")
        rb = rest.index("]", lb)
        dateField = rest[lb+1:rb]               #  17/May/2015:10:05:03 +0000
        dayOnly = dateField.split(":", 1)[0]   # take only dd/Mon/yyyy
        dateObj = datetime.datetime.strptime(dayOnly, "%d/%b/%Y").date()

        # Extract request between the next pair of quotes
        q1 = rest.index('"', rb)
        q2 = rest.index('"', q1+1)
        request = rest[q1+1:q2]                 # GET /path HTTP/1.1
        parts = request.split()

        method = parts[0] if len(parts) >= 1 else ""
        resource = parts[1] if len(parts) >= 2 else ""

        return host, dateObj, method, resource
    except Exception:
        return None

def RangeCheck(counter, set=30):
    items = list(counter.items())
    if not items:
        return []
    # deterministic: sort by key asc, then stable sort by count desc
    items.sort(key=operator.itemgetter(0))
    items.sort(key=operator.itemgetter(1), reverse=True)

    cutoff_index = min(set, len(items)) - 1
    cutoff_count = items[cutoff_index][1]
    return [it for it in items if it[1] >= cutoff_count]

def main():
    log_path, startTxt, endTxt, start_date, end_date = ParsingCLI(sys.argv)

    print(f"Analyze {log_path} between {startTxt} and {endTxt}")

    hosts = collections.Counter()
    resources = collections.Counter()

    LinesTotal = LinesToKeep = 0

    try:
        with open(log_path, "r", encoding="utf-8", errors="ignore") as fileWeb:
            for line in fileWeb:
                LinesTotal += 1
                parsed = ParseCLF(line)
                if not parsed:
                    continue
                host, Date, Method, resource_path = parsed
                if start_date <= Date <= end_date:
                    LinesToKeep += 1
                    hosts[host] += 1
                    if Method == "GET":
                        resources[resource_path] += 1
    except FileNotFoundError:
        print(f"Error: log file not found: {log_path}")
        sys.exit(1)

    # Summary line
    print(f"{LinesToKeep}/{LinesTotal} lines from {startTxt} to {endTxt}\n")

    # Hosts report
    top_hosts = RangeCheck(hosts, 30)
    print(f"Top {len(top_hosts)} most active hosts:")
    for i, (h, c) in enumerate(top_hosts, 1):
        print(f"  No. {i}: {h} {c}")

    print()

    # Resources report
    top_resources = RangeCheck(resources, 30)
    print(f"Top {len(top_resources)} most downloaded resources:")
    for i, (r, c) in enumerate(top_resources, 1):
        print(f"  No. {i}: {r} {c}")

if __name__ == "__main__":
    main()


# Formatting output to the sample was honestly the trickiest part, used AI to help with that.






    




       
   
       


