# Name: Judah Alter
# Date: 9/8/2025
# Assignment: (Assignment #1)
# Due Date: 9/12/2025
# About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes)
# Assumptions: (write any assumptions made here (ex: assumes correct user input))
# All work below was performed solely by Judah Alter.
# I [did used] code generated by an AI tool.

import sys 
import random

defect = 0 
cooperate = 1
roundCounter = 0

def reward(MyAction , OpponentAction):
    if MyAction == defect and OpponentAction == defect:
        return 1
    elif MyAction == defect and OpponentAction == cooperate:
        return 5
    elif MyAction == cooperate and OpponentAction == defect:
        return 0
    else:
        return 3
    
def rangeReward(beg,end,myHistory,oppHistory):
    total = 0

    for i in range(beg,min(end,len(myHistory))):
        total += reward(myHistory[i],oppHistory[i])
    return total

def alwaysCooperate(myHistory,oppHistory):
    return cooperate

def alwaysDefect(myHistory,oppHistory):
    return defect

def probeAndLock(myHistory,oppHistory):
    if(len(myHistory) < 20):
        return defect
    elif(len(myHistory) < 40):
        return cooperate
    else:
        reward1=rangeReward(0,20,myHistory,oppHistory)
        reward2=rangeReward(20,40,myHistory,oppHistory)
        if reward1 > reward2:
            return defect
        else:
            return cooperate
        
def CheckProbeAndLock(myHistory,oppHistory):
    return probeAndLock(myHistory,oppHistory)


def continiousProbe(myHistory,oppHistory):
    n=len(myHistory)
    if n== roundCounter:
        return defect
    if n==1:
        return cooperate
    DSum = DCount = CSum = CCount = 0
    for a, b in zip(myHistory, oppHistory):
        if a == defect:
            DSum += reward(a, b); DCount += 1
        else:
            CSum += reward(a, b); CCount += 1
    DAverage = DSum / DCount if DCount else 0.0
    CAverage = CSum / CCount if CCount else 0.0
    return cooperate if CAverage > DAverage else defect

def DefectUntilCooperate(myHistory,oppHistory):
    return cooperate if 1 in oppHistory else defect

def opponetCooperatePercentage(myHistory,oppHistory,ValCheck):

    if not oppHistory:
        return defect
    else:
        rate = sum(1 for x in oppHistory if x == cooperate) / len(oppHistory)
        return cooperate if rate > ValCheck else defect                         # 0.5 is the threshold, can be changed. Will come back and check this later
    
def opponentCooperate10Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.10)

def opponetCooperate50Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.50)    
    
def opponetCooperate90Percent(myHistory,oppHistory):
    return opponetCooperatePercentage(myHistory,oppHistory,0.90)

def randomChoice50(myHistory,oppHistory):
    return 1 if random.getrandbits(1) else 0

STRATEGIES = [
    ("alwaysCooperate", alwaysCooperate),
    ("alwaysDefect", alwaysDefect),
    ("probeAndLock", probeAndLock),
    ("continiousProbe", continiousProbe),
    ("defectUntilCooperate", DefectUntilCooperate),
    ("opponentCooperate10Percentage", opponentCooperate10Percent),
    ("opponentCooperate50Percentage", opponetCooperate50Percent),
    ("opponentCooperate90Percentage", opponetCooperate90Percent),
    ("random50", randomChoice50),
    # ("JudahAAlter", strategy_FirstLast),  # enable once finalized
]

def PlayRound(GameA, GameB,Matches):
    AHistory = []
    BHistory = []
    ATotal = 0
    BTotal = 0
    for i in range(Matches):
        AMatch = GameA(AHistory, BHistory)
        BMatch = GameB(BHistory, AHistory)
        ATotal += reward(AMatch, BMatch)
        BTotal += reward(BMatch, AMatch)
        AHistory.append(AMatch)
        BHistory.append(BMatch)
    return ATotal, BTotal

def main():

    # Prompt user for rounds (any non-negative integer, default 2000)
    defaultRound = 2000
    while True:
        try:
            roundsInput = input(f"Enter number of rounds (any non-negative integer, default {defaultRound}): ")
            if roundsInput.strip() == "":
                rounds = defaultRound
                break
            rounds = int(roundsInput)
            if rounds >= 0:
                break
            else:
                print("Please enter a non-negative integer.")
        except ValueError:
            print("Please enter a valid integer.")

    # Prompt user for k (any non-negative integer, default 8)
    maxK = len(STRATEGIES)
    defaultStrat = 8 if maxK >= 8 else maxK
    while True:
        try:
            k_input = input(f"Enter number of strategies to use (0 to {maxK}, default {defaultStrat}): ")
            if k_input.strip() == "":
                k = defaultStrat
                break
            k = int(k_input)
            if 0 <= k <= maxK:
                break
            else:
                print(f"Please enter a number between 0 and {maxK}.")  
        except ValueError:
            print("Please enter a valid integer.")

    print(f"num_of_iterations: {rounds}, num_of_stratiges: {k}\n")

    FunctionNames = STRATEGIES[:k]
    totals = [0 for _ in range(len(FunctionNames))]

    for i in range(len(FunctionNames)):
        for j in range(i+1, len(FunctionNames)):
            AName, AFunction = FunctionNames[i]
            BName, BFunction = FunctionNames[j]
            ATotal, BTotal = PlayRound(AFunction, BFunction, rounds)
            totals[i] += ATotal
            totals[j] += BTotal
    for (name, _), total in zip(FunctionNames, totals):
        print(f"{name}: {total}")

if __name__ == "__main__":
    main()


# Linprog executable file using sftp make a copy. Used to run on linprog.














