# Name: Judah Alter
# Date: 10/13/2025
# Assignment: (Assignment #1)
# Due Date: 10/13/2025
# About this project: Game Theory Project- similar to Prisoner's Dilemma project 1 but on a 2d grid.
# Assumptions: ex: assumes correct user input
# All work below was performed solely by Judah Alter.
# I [did used] code generated by an AI tool.

import sys  # system functions
import random  # random number generation
from time import perf_counter  # timing

defect = 1  # defect action
cooperate = 0  # cooperate action

payoffMatrix = [  # payoff matrix
    [3, 0],
    [5, 1],   
]

def parse_cli(argv):
    if len(argv) < 3:
        print("Usage: python3 Alter_J_assignment3.py grid_size steps num_processes")
        sys.exit(1)
    size  = int(argv[1])
    steps = int(argv[2])
    # num_processes accepted to satisfy spec, but unused in this sequential file
    nprocs = int(argv[3]) if len(argv) >= 4 else 1
    return size, steps, nprocs

# Grid Helpers and Initialization
def makeShape(size, value):
    return [[value for _ in range(size)] for _ in range(size)]


def initializeActionGrid1(size, grid):
    # top half coop, bottom half defect
    for i in range(size):
        for j in range(size):
            grid[i][j] = cooperate if i < size/2 else defect

def initializeActionGrid2(size, grid):
    # all coop except main diagonal defects
    for i in range(size):
        for j in range(size):
            grid[i][j] = defect if i == j else cooperate

def initializeActionGrid3(size, grid):
    # all coop, one defect at center
    for i in range(size):
        for j in range(size):
            grid[i][j] = cooperate
    grid[size // 2][size // 2] = defect

def initializeActionGrid4(size, grid):
    # all coop, one defect at (1,1) if it exists else (0,0)
    for i in range(size):
        for j in range(size):
            grid[i][j] = cooperate
    if size > 1:
        grid[1][1] = defect
    else:
        grid[0][0] = defect


def getNeighbors(i, j, size):
    neighbors = []
    if i > 0:            neighbors.append((i-1, j))  # North
    if i + 1 < size:     neighbors.append((i+1, j))  # South
    if j + 1 < size:     neighbors.append((i, j+1))  # East
    if j > 0:            neighbors.append((i, j-1))  # West
    return neighbors

# Reward Computation
def computeReward(i, j, actionGrid, size):
    myAction = actionGrid[i][j]
    total = 0
    # my payoff against each neighbor (row = me, col = neighbor)
    for ni, nj in getNeighbors(i, j, size):
        neighborAction = actionGrid[ni][nj]
        total += payoffMatrix[myAction][neighborAction]
    return total

# Sequential simulation of the grid game

def run_simulation_seq(initF, size, steps, out_name):
    actionGrid = makeShape(size, cooperate)
    rewardGrid = makeShape(size, 0)
    workGrid   = makeShape(size, cooperate)

# Determinsitc init 
    initF(size, actionGrid)
    print(f"{initF.__name__}, size={size}, steps={steps}, fName={out_name}")

    for ss in range(steps):
        # (1) compute rewardGrid from current actionGrid
        for i in range(size):
            for j in range(size):
                rewardGrid[i][j] = computeReward(i, j, actionGrid, size)

        # (2) decide new action by striclty greater reward among {self + neighbors}
        for i in range(size):
            for j in range(size):
                 bestReward = rewardGrid[i][j]
                 newAction = actionGrid[i][j]
                 for ii, jj in getNeighbors(i, j, size):
                    if rewardGrid[ii][jj] > bestReward:  
                        bestReward = rewardGrid[ii][jj]
                        newAction  = actionGrid[ii][jj]
                 workGrid[i][j] = newAction

        # (3) commit workGrid to actionGrid
        for i in range(size):
            for j in range(size):
                actionGrid[i][j] = workGrid[i][j]
        
        # screen counts (should match the reference output)
        coop = sum(1 for i in range(size) for j in range(size) if actionGrid[i][j] == cooperate)
        defe = size*size - coop
        print(f"step {ss}: {coop} cooperates, {defe} defects")

    with open(out_name, "w") as f:
        for i in range(size):
            f.write(f"{i}: {actionGrid[i]}\n")    
    
def run_all(size, steps, nprocs):
    # DO NOT include initializeActionGrid0 (random) in grading runs
    jobs = [
        (initializeActionGrid1, f"output_grid1_{size}_{steps}_seq.txt"),
        (initializeActionGrid2, f"output_grid2_{size}_{steps}_seq.txt"),
        (initializeActionGrid3, f"output_grid3_{size}_{steps}_seq.txt"),
        (initializeActionGrid4, f"output_grid4_{size}_{steps}_seq.txt"),
    ]
    t0 = perf_counter()
    for initF, out_name in jobs:
        run_simulation_seq(initF, size, steps, out_name)
    t1 = perf_counter()
    
    print(f"Total time (all 4 sims): {t1 - t0:.3f} sec with nprocs={nprocs}")    
            
if __name__ == "__main__":
    size, steps, nprocs = parse_cli(sys.argv)
    run_all(size, steps, nprocs)




    










    




